In [143]:
print("hello")

hello

In [144]:
import pandas as pd

In [145]:
data=pd.read_csv("twitter_training.csv")

In [146]:
data.head()

,2401,Borderlands,Positive,"im getting on borderlands and i will murder you all ,"
0,2401,Borderlands,Positive,I am coming to the borders and I will kill you...
1,2401,Borderlands,Positive,im getting on borderlands and i will kill you ...
2,2401,Borderlands,Positive,im coming on borderlands and i will murder you...
3,2401,Borderlands,Positive,im getting on borderlands 2 and i will murder ...
4,2401,Borderlands,Positive,im getting into borderlands and i can murder y...

In [147]:
data=data.sample(15000,random_state=42)

In [148]:
data.shape

(15000, 4)

In [149]:
## Data Exploration

In [150]:
data['Positive'].value_counts()

Positive
Negative      4488
Positive      4275
Neutral       3568
Irrelevant    2669
Name: count, dtype: int64

In [151]:
data.isnull().sum()

2401                                                       0
Borderlands                                                0
Positive                                                   0
im getting on borderlands and i will murder you all ,    151
dtype: int64

In [152]:
data.duplicated().sum()

np.int64(127)

In [153]:
data=data.dropna()

In [154]:
data.isnull().sum()

2401                                                     0
Borderlands                                              0
Positive                                                 0
im getting on borderlands and i will murder you all ,    0
dtype: int64

In [155]:
data.drop_duplicates(inplace=True)

In [156]:
data.duplicated().sum()

np.int64(0)

In [157]:
data.head()

,2401,Borderlands,Positive,"im getting on borderlands and i will murder you all ,"
34877,6792,Fortnite,Irrelevant,went to go in george's room to find his door w...
21704,4115,CS-GO,Positive,Yo this looks LIT! Team:GO/Overwatch combo
47008,5665,HomeDepot,Negative,Pay attention executive administrators. While ...
7969,9369,Overwatch,Irrelevant,Guy looked at me and says my name was put on t...
454,2476,Borderlands,Positive,one

In [158]:
data.drop(columns=['2401','Borderlands'],inplace=True)

In [159]:
data.head(1)

         Positive im getting on borderlands and i will murder you all ,
34877  Irrelevant  went to go in george's room to find his door w...

In [160]:
data.rename(columns={
    'Positive':'Sentiment',
    'im getting on borderlands and i will murder you all ,':'Tweets'
    },inplace=True)

In [161]:
data.head()

        Sentiment                                             Tweets
34877  Irrelevant  went to go in george's room to find his door w...
21704    Positive         Yo this looks LIT! Team:GO/Overwatch combo
47008    Negative  Pay attention executive administrators. While ...
7969   Irrelevant  Guy looked at me and says my name was put on t...
454      Positive                                                one

In [162]:
data['Sentiment'].value_counts()

Sentiment
Negative      4418
Positive      4201
Neutral       3508
Irrelevant    2619
Name: count, dtype: int64

In [163]:
data=data[(data['Sentiment']=='Positive') | (data['Sentiment']=='Negative') |
  (data['Sentiment']=='Neutral') ]

In [164]:
data.head()

      Sentiment                                             Tweets
21704  Positive         Yo this looks LIT! Team:GO/Overwatch combo
47008  Negative  Pay attention executive administrators. While ...
454    Positive                                                one
58076  Negative       @Rainbow6Game Server are Available in Xbox 🥺
40659  Positive  so Awesome siege attempt... strangest bleeding...

In [165]:
data['Sentiment'].value_counts()

Sentiment
Negative    4418
Positive    4201
Neutral     3508
Name: count, dtype: int64

In [166]:
# Feature Encoding 
from sklearn.preprocessing import LabelEncoder

In [167]:
label = LabelEncoder()

In [168]:
data['Sentiment']=label.fit_transform(data['Sentiment'])

In [169]:
data['Sentiment']

21704    2
47008    0
454      2
58076    0
40659    2
        ..
57537    2
7757     2
3887     0
22629    1
56434    2
Name: Sentiment, Length: 12127, dtype: int64

In [170]:
from tensorflow.keras.preprocessing.text import Tokenizer


# Create a NEW tokenizer
tokenizer = Tokenizer()

# Fit tokenizer
tokenizer.fit_on_texts(data['Tweets']) # fit = learn the vocabulary

# Convert text to sequences
sequences = tokenizer.texts_to_sequences(data['Tweets'])

In [171]:
from keras.utils import pad_sequences

In [172]:
# A neural network generally needs inputs with the same shape/length.
sequences=pad_sequences(sequences,padding='pre')

"I love this"             → [5, 1, 3]

"I love this movie"       → [5, 1, 3, 2]

"I really love this movie" → [5, 6, 1, 3, 2]

sequences=pad_sequences(sequences,padding='pre')

[0, 0, 5, 1, 3]
[0, 5, 1, 3, 2]
[5, 6, 1, 3, 2]

In [173]:
sequences

array([[    0,     0,     0, ...,    94,   196,  2524],
       [    0,     0,     0, ...,     6,  2162,  3097],
       [    0,     0,     0, ...,     0,     0,    51],
       ...,
       [    0,     0,     0, ...,    19,   222,  6167],
       [    0,     0,     0, ...,    42,    73, 17871],
       [    0,     0,     0, ...,   791,  1030,  6491]],
      shape=(12127, 99), dtype=int32)

In [174]:
from tensorflow.keras.layers import SimpleRNN,Dense,Input,Embedding
from tensorflow.keras.models import Sequential

In [175]:
X=sequences

In [176]:
y=data['Sentiment'].values

In [177]:
y

array([2, 0, 2, ..., 0, 1, 2], shape=(12127,))

In [178]:
from sklearn.model_selection import train_test_split

In [179]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [180]:
X_train.shape

(9701, 99)

In [181]:
model=Sequential()
model.add(SimpleRNN(32,input_shape=(99,1),return_sequences=False))
model.add(Dense(3,activation='softmax'))

d:\aashish\generative ai course\Deep Learning\RNN\venv\Lib\site-packages\keras\src\layers\rnn\rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)

In [182]:
model.summary()

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ simple_rnn_3 (SimpleRNN)        │ (None, 32)             │         1,088 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_4 (Dense)                 │ (None, 3)              │            99 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,187 (4.64 KB)

 Trainable params: 1,187 (4.64 KB)

 Non-trainable params: 0 (0.00 B)

In [183]:
model.compile(optimizer="adam",metrics=['accuracy'],loss='sparse_categorical_crossentropy')

In [184]:
model.fit(X_train,y_train,epochs=10,validation_data=(X_test,y_test),batch_size=64)

Epoch 1/10

152/152 ━━━━━━━━━━━━━━━━━━━━ 5s 20ms/step - accuracy: 0.3570 - loss: 1.1327 - val_accuracy: 0.3702 - val_loss: 1.0922
Epoch 2/10
152/152 ━━━━━━━━━━━━━━━━━━━━ 4s 23ms/step - accuracy: 0.3746 - loss: 1.0934 - val_accuracy: 0.3454 - val_loss: 1.1054
Epoch 3/10
152/152 ━━━━━━━━━━━━━━━━━━━━ 5s 33ms/step - accuracy: 0.3578 - loss: 1.0934 - val_accuracy: 0.3607 - val_loss: 1.0952
Epoch 4/10
152/152 ━━━━━━━━━━━━━━━━━━━━ 5s 31ms/step - accuracy: 0.3674 - loss: 1.0940 - val_accuracy: 0.3660 - val_loss: 1.0944
Epoch 5/10
152/152 ━━━━━━━━━━━━━━━━━━━━ 5s 30ms/step - accuracy: 0.3741 - loss: 1.0893 - val_accuracy: 0.3664 - val_loss: 1.0926
Epoch 6/10
152/152 ━━━━━━━━━━━━━━━━━━━━ 5s 31ms/step - accuracy: 0.3720 - loss: 1.0886 - val_accuracy: 0.3491 - val_loss: 1.0949
Epoch 7/10
152/152 ━━━━━━━━━━━━━━━━━━━━ 4s 26ms/step - accuracy: 0.3708 - loss: 1.0880 - val_accuracy: 0.3718 - val_loss: 1.0906
Epoch 8/10
152/152 ━━━━━━━━━━━━━━━━━━━━ 4s 27ms/step - accuracy: 0.3697 - loss: 1.0867 - val_accuracy: 0.3702 - val_loss: 1.0878
Epoch 9/10
152/152 ━━━━━━━━━━━━━━━━━━━━ 5s 33ms/step - accuracy: 0.3789 - loss: 1.0842 - val_accuracy: 0.3623 - val_loss: 1.0915
Epoch 10/10
152/152 ━━━━━━━━━━━━━━━━━━━━ 5s 30ms/step - accuracy: 0.3710 - loss: 1.0858 - val_accuracy: 0.3726 - val_loss: 1.0906

In [185]:
vocab_size=len(tokenizer.word_index)+1

In [186]:
vocab_size

17872

In [187]:
model_2=Sequential()
model_2.add(Input(shape=(99,)))
model_2.add(Embedding(input_dim=vocab_size,output_dim=64))
model_2.add(Dense(3,activation='softmax'))

In [188]:
model_2.summary()

Model: "sequential_5"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_3 (Embedding)         │ (None, 99, 64)         │     1,143,808 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_5 (Dense)                 │ (None, 99, 3)          │           195 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,144,003 (4.36 MB)

 Trainable params: 1,144,003 (4.36 MB)

 Non-trainable params: 0 (0.00 B)

In [189]:
model_final=Sequential([
    Embedding(
        input_dim=vocab_size,
        output_dim=128,
        input_length=99,
        mask_zero=True
        ),
SimpleRNN(32),
Dense(3,activation='softmax')
])

d:\aashish\generative ai course\Deep Learning\RNN\venv\Lib\site-packages\keras\src\layers\core\embedding.py:123: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(

In [190]:
model_final.compile(
    optimizer='adam',
    metrics=['accuracy'],
    loss='sparse_categorical_crossentropy',
    )

In [191]:
model_final.summary()

Model: "sequential_6"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_4 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn_4 (SimpleRNN)        │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_6 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [197]:
model_final.fit(X_train,y_train,epochs=100,validation_data=(X_test,y_test),batch_size=64)

Epoch 1/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 18s 119ms/step - accuracy: 0.9815 - loss: 0.0374 - val_accuracy: 0.6987 - val_loss: 1.1538
Epoch 2/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 21s 118ms/step - accuracy: 0.9818 - loss: 0.0358 - val_accuracy: 0.6917 - val_loss: 1.1891
Epoch 3/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 21s 120ms/step - accuracy: 0.9809 - loss: 0.0360 - val_accuracy: 0.6908 - val_loss: 1.2191
Epoch 4/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 23s 150ms/step - accuracy: 0.9825 - loss: 0.0350 - val_accuracy: 0.6921 - val_loss: 1.2569
Epoch 5/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 35s 109ms/step - accuracy: 0.9821 - loss: 0.0359 - val_accuracy: 0.6789 - val_loss: 1.2683
Epoch 6/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 19s 123ms/step - accuracy: 0.9644 - loss: 0.0905 - val_accuracy: 0.6641 - val_loss: 1.2190
Epoch 7/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 18s 119ms/step - accuracy: 0.9663 - loss: 0.0797 - val_accuracy: 0.6653 - val_loss: 1.2623
Epoch 8/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 19s 122ms/step - accuracy: 0.9802 - loss: 0.0402 - val_accuracy: 0.6830 - val_loss: 1.2530
Epoch 9/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 18s 119ms/step - accuracy: 0.9827 - loss: 0.0355 - val_accuracy: 0.6843 - val_loss: 1.2697
Epoch 10/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 19s 126ms/step - accuracy: 0.9817 - loss: 0.0348 - val_accuracy: 0.6826 - val_loss: 1.2887
Epoch 11/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 18s 121ms/step - accuracy: 0.9814 - loss: 0.0352 - val_accuracy: 0.6826 - val_loss: 1.3009
Epoch 12/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 21s 125ms/step - accuracy: 0.9805 - loss: 0.0348 - val_accuracy: 0.6838 - val_loss: 1.3194
Epoch 13/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 19s 124ms/step - accuracy: 0.9825 - loss: 0.0344 - val_accuracy: 0.6847 - val_loss: 1.3253
Epoch 14/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 19s 125ms/step - accuracy: 0.9822 - loss: 0.0344 - val_accuracy: 0.6814 - val_loss: 1.3387
Epoch 15/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 19s 124ms/step - accuracy: 0.9819 - loss: 0.0340 - val_accuracy: 0.6810 - val_loss: 1.3479
Epoch 16/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 19s 127ms/step - accuracy: 0.9821 - loss: 0.0345 - val_accuracy: 0.6826 - val_loss: 1.3592
Epoch 17/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 20s 129ms/step - accuracy: 0.9819 - loss: 0.0342 - val_accuracy: 0.6772 - val_loss: 1.3656
Epoch 18/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 19s 126ms/step - accuracy: 0.9812 - loss: 0.0342 - val_accuracy: 0.6822 - val_loss: 1.3803
Epoch 19/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 19s 124ms/step - accuracy: 0.9817 - loss: 0.0341 - val_accuracy: 0.6797 - val_loss: 1.3833
Epoch 20/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 20s 129ms/step - accuracy: 0.9810 - loss: 0.0339 - val_accuracy: 0.6896 - val_loss: 1.3894
Epoch 21/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 20s 125ms/step - accuracy: 0.9812 - loss: 0.0338 - val_accuracy: 0.6814 - val_loss: 1.4018
Epoch 22/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 19s 125ms/step - accuracy: 0.9813 - loss: 0.0342 - val_accuracy: 0.6847 - val_loss: 1.4031
Epoch 23/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 27s 169ms/step - accuracy: 0.9815 - loss: 0.0336 - val_accuracy: 0.6810 - val_loss: 1.4093
Epoch 24/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 43s 182ms/step - accuracy: 0.9807 - loss: 0.0339 - val_accuracy: 0.6785 - val_loss: 1.4207
Epoch 25/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 29s 193ms/step - accuracy: 0.9820 - loss: 0.0335 - val_accuracy: 0.6789 - val_loss: 1.4326
Epoch 26/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 25s 164ms/step - accuracy: 0.9817 - loss: 0.0335 - val_accuracy: 0.6764 - val_loss: 1.4376
Epoch 27/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 22s 146ms/step - accuracy: 0.9812 - loss: 0.0336 - val_accuracy: 0.6851 - val_loss: 1.4446
Epoch 28/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 23s 148ms/step - accuracy: 0.9824 - loss: 0.0333 - val_accuracy: 0.6768 - val_loss: 1.4514
Epoch 29/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 23s 150ms/step - accuracy: 0.9827 - loss: 0.0332 - val_accuracy: 0.6859 - val_loss: 1.4494
Epoch 30/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 23s 148ms/step - accuracy: 0.9819 - loss: 0.0333 - val_accuracy: 0.6818 - val_loss: 1.4667
Epoch 31/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 66s 303ms/step - accuracy: 0.9815 - loss: 0.0330 - val_accuracy: 0.6830 - val_loss: 1.4700
Epoch 32/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 46s 290ms/step - accuracy: 0.9813 - loss: 0.0333 - val_accuracy: 0.6793 - val_loss: 1.4767
Epoch 33/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 67s 183ms/step - accuracy: 0.9812 - loss: 0.0329 - val_accuracy: 0.6838 - val_loss: 1.4888
Epoch 34/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 36s 147ms/step - accuracy: 0.9818 - loss: 0.0330 - val_accuracy: 0.6735 - val_loss: 1.5119
Epoch 35/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 21s 140ms/step - accuracy: 0.9824 - loss: 0.0328 - val_accuracy: 0.6843 - val_loss: 1.5010
Epoch 36/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 22s 142ms/step - accuracy: 0.9814 - loss: 0.0330 - val_accuracy: 0.6805 - val_loss: 1.5135
Epoch 37/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 40s 130ms/step - accuracy: 0.9817 - loss: 0.0326 - val_accuracy: 0.6838 - val_loss: 1.5211
Epoch 38/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 21s 140ms/step - accuracy: 0.9825 - loss: 0.0325 - val_accuracy: 0.6748 - val_loss: 1.5331
Epoch 39/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 42s 143ms/step - accuracy: 0.9814 - loss: 0.0328 - val_accuracy: 0.6797 - val_loss: 1.5315
Epoch 40/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 23s 150ms/step - accuracy: 0.9817 - loss: 0.0327 - val_accuracy: 0.6797 - val_loss: 1.5361
Epoch 41/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 40s 141ms/step - accuracy: 0.9810 - loss: 0.0328 - val_accuracy: 0.6785 - val_loss: 1.5459
Epoch 42/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 23s 154ms/step - accuracy: 0.9819 - loss: 0.0325 - val_accuracy: 0.6843 - val_loss: 1.5565
Epoch 43/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 22s 144ms/step - accuracy: 0.9820 - loss: 0.0324 - val_accuracy: 0.6760 - val_loss: 1.5576
Epoch 44/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 22s 142ms/step - accuracy: 0.9820 - loss: 0.0324 - val_accuracy: 0.6723 - val_loss: 1.5681
Epoch 45/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 22s 141ms/step - accuracy: 0.9821 - loss: 0.0321 - val_accuracy: 0.6801 - val_loss: 1.5796
Epoch 46/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 42s 144ms/step - accuracy: 0.9830 - loss: 0.0322 - val_accuracy: 0.6822 - val_loss: 1.5843
Epoch 47/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 21s 140ms/step - accuracy: 0.9822 - loss: 0.0325 - val_accuracy: 0.6744 - val_loss: 1.5997
Epoch 48/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 21s 139ms/step - accuracy: 0.9818 - loss: 0.0326 - val_accuracy: 0.6772 - val_loss: 1.6010
Epoch 49/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 22s 144ms/step - accuracy: 0.9825 - loss: 0.0319 - val_accuracy: 0.6653 - val_loss: 1.6276
Epoch 50/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 24s 158ms/step - accuracy: 0.9693 - loss: 0.0701 - val_accuracy: 0.6290 - val_loss: 1.5469
Epoch 51/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 21s 138ms/step - accuracy: 0.9630 - loss: 0.0899 - val_accuracy: 0.6682 - val_loss: 1.4040
Epoch 52/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 22s 145ms/step - accuracy: 0.9818 - loss: 0.0380 - val_accuracy: 0.6682 - val_loss: 1.4166
Epoch 53/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 39s 129ms/step - accuracy: 0.9831 - loss: 0.0326 - val_accuracy: 0.6744 - val_loss: 1.4109
Epoch 54/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 25s 165ms/step - accuracy: 0.9822 - loss: 0.0323 - val_accuracy: 0.6752 - val_loss: 1.4260
Epoch 55/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 40s 154ms/step - accuracy: 0.9827 - loss: 0.0321 - val_accuracy: 0.6785 - val_loss: 1.4339
Epoch 56/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 22s 142ms/step - accuracy: 0.9822 - loss: 0.0320 - val_accuracy: 0.6781 - val_loss: 1.4435
Epoch 57/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 22s 145ms/step - accuracy: 0.9817 - loss: 0.0319 - val_accuracy: 0.6777 - val_loss: 1.4527
Epoch 58/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 22s 144ms/step - accuracy: 0.9826 - loss: 0.0319 - val_accuracy: 0.6772 - val_loss: 1.4666
Epoch 59/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 21s 139ms/step - accuracy: 0.9823 - loss: 0.0319 - val_accuracy: 0.6772 - val_loss: 1.4725
Epoch 60/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 41s 136ms/step - accuracy: 0.9817 - loss: 0.0320 - val_accuracy: 0.6818 - val_loss: 1.4789
Epoch 61/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 22s 147ms/step - accuracy: 0.9820 - loss: 0.0320 - val_accuracy: 0.6772 - val_loss: 1.4874
Epoch 62/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 22s 145ms/step - accuracy: 0.9818 - loss: 0.0321 - val_accuracy: 0.6822 - val_loss: 1.4972
Epoch 63/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 21s 140ms/step - accuracy: 0.9823 - loss: 0.0319 - val_accuracy: 0.6818 - val_loss: 1.5000
Epoch 64/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 23s 150ms/step - accuracy: 0.9824 - loss: 0.0319 - val_accuracy: 0.6793 - val_loss: 1.5021
Epoch 65/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 40s 144ms/step - accuracy: 0.9821 - loss: 0.0322 - val_accuracy: 0.6830 - val_loss: 1.5095
Epoch 66/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 40s 137ms/step - accuracy: 0.9822 - loss: 0.0319 - val_accuracy: 0.6793 - val_loss: 1.5133
Epoch 67/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 22s 146ms/step - accuracy: 0.9820 - loss: 0.0319 - val_accuracy: 0.6814 - val_loss: 1.5129
Epoch 68/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 22s 144ms/step - accuracy: 0.9828 - loss: 0.0319 - val_accuracy: 0.6826 - val_loss: 1.5248
Epoch 69/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 22s 145ms/step - accuracy: 0.9823 - loss: 0.0319 - val_accuracy: 0.6822 - val_loss: 1.5340
Epoch 70/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 22s 142ms/step - accuracy: 0.9820 - loss: 0.0320 - val_accuracy: 0.6777 - val_loss: 1.5267
Epoch 71/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 22s 146ms/step - accuracy: 0.9829 - loss: 0.0319 - val_accuracy: 0.6838 - val_loss: 1.5440
Epoch 72/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 40s 134ms/step - accuracy: 0.9821 - loss: 0.0319 - val_accuracy: 0.6826 - val_loss: 1.5474
Epoch 73/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 23s 146ms/step - accuracy: 0.9821 - loss: 0.0318 - val_accuracy: 0.6830 - val_loss: 1.5462
Epoch 74/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 22s 141ms/step - accuracy: 0.9829 - loss: 0.0318 - val_accuracy: 0.6830 - val_loss: 1.5541
Epoch 75/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 22s 142ms/step - accuracy: 0.9830 - loss: 0.0319 - val_accuracy: 0.6838 - val_loss: 1.5713
Epoch 76/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 40s 136ms/step - accuracy: 0.9824 - loss: 0.0319 - val_accuracy: 0.6863 - val_loss: 1.5648
Epoch 77/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 23s 148ms/step - accuracy: 0.9825 - loss: 0.0319 - val_accuracy: 0.6822 - val_loss: 1.5672
Epoch 78/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 39s 131ms/step - accuracy: 0.9825 - loss: 0.0317 - val_accuracy: 0.6834 - val_loss: 1.5808
Epoch 79/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 23s 146ms/step - accuracy: 0.9822 - loss: 0.0320 - val_accuracy: 0.6822 - val_loss: 1.5923
Epoch 80/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 22s 144ms/step - accuracy: 0.9832 - loss: 0.0319 - val_accuracy: 0.6851 - val_loss: 1.6039
Epoch 81/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 23s 151ms/step - accuracy: 0.9828 - loss: 0.0318 - val_accuracy: 0.6838 - val_loss: 1.6203
Epoch 82/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 39s 133ms/step - accuracy: 0.9824 - loss: 0.0319 - val_accuracy: 0.6838 - val_loss: 1.6243
Epoch 83/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 22s 146ms/step - accuracy: 0.9817 - loss: 0.0319 - val_accuracy: 0.6863 - val_loss: 1.6144
Epoch 84/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 41s 146ms/step - accuracy: 0.9826 - loss: 0.0316 - val_accuracy: 0.6830 - val_loss: 1.6157
Epoch 85/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 40s 138ms/step - accuracy: 0.9821 - loss: 0.0316 - val_accuracy: 0.6876 - val_loss: 1.6251
Epoch 86/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 41s 139ms/step - accuracy: 0.9826 - loss: 0.0316 - val_accuracy: 0.6855 - val_loss: 1.6313
Epoch 87/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 40s 132ms/step - accuracy: 0.9831 - loss: 0.0315 - val_accuracy: 0.6876 - val_loss: 1.6469
Epoch 88/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 22s 140ms/step - accuracy: 0.9823 - loss: 0.0318 - val_accuracy: 0.6904 - val_loss: 1.6410
Epoch 89/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 22s 142ms/step - accuracy: 0.9815 - loss: 0.0318 - val_accuracy: 0.6797 - val_loss: 1.6202
Epoch 90/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 40s 132ms/step - accuracy: 0.9732 - loss: 0.0601 - val_accuracy: 0.6443 - val_loss: 1.5754
Epoch 91/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 22s 142ms/step - accuracy: 0.9767 - loss: 0.0502 - val_accuracy: 0.6546 - val_loss: 1.5395
Epoch 92/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 40s 137ms/step - accuracy: 0.9822 - loss: 0.0334 - val_accuracy: 0.6603 - val_loss: 1.5211
Epoch 93/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 25s 163ms/step - accuracy: 0.9828 - loss: 0.0318 - val_accuracy: 0.6603 - val_loss: 1.5327
Epoch 94/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 20s 129ms/step - accuracy: 0.9829 - loss: 0.0317 - val_accuracy: 0.6575 - val_loss: 1.5433
Epoch 95/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 19s 125ms/step - accuracy: 0.9829 - loss: 0.0315 - val_accuracy: 0.6570 - val_loss: 1.5520
Epoch 96/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 26s 173ms/step - accuracy: 0.9824 - loss: 0.0315 - val_accuracy: 0.6579 - val_loss: 1.5612
Epoch 97/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 49s 225ms/step - accuracy: 0.9826 - loss: 0.0316 - val_accuracy: 0.6550 - val_loss: 1.5707
Epoch 98/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 32s 212ms/step - accuracy: 0.9821 - loss: 0.0314 - val_accuracy: 0.6558 - val_loss: 1.5793
Epoch 99/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 35s 226ms/step - accuracy: 0.9827 - loss: 0.0314 - val_accuracy: 0.6546 - val_loss: 1.5876
Epoch 100/100
152/152 ━━━━━━━━━━━━━━━━━━━━ 38s 202ms/step - accuracy: 0.9819 - loss: 0.0315 - val_accuracy: 0.6542 - val_loss: 1.5926

In [193]:
import pickle

In [195]:
with open ('tokenizer.pkl','wb') as file:
    pickle.dump(tokenizer,file)

In [198]:
model_final.save('model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.